### ISSUE TITLE
Progress blocked

### ISSUE THREAD

**Issue by AntoineSidem** [KandleTeam/kandle#47]
We worked very hard this week to do proper mocking mechanisms for the database and authentication systems. As a result, about 600 lines of code in our production implementation stay untested, which leaves no room for the 80% coverage threshold. We are unable to merge our abstractions into master. Other branches are relying on the abstraction & mocking to provide good tests and coverage on the old code, so they are blocked from merging as well.
Much of the tedium we encountered last week was due to the fact that we abstracted away our dependencies too late. But had we done it earlier, it would have been an even larger part of our codebase, and fall even shorted from the coverage threshold.
We understand that CodeCoverage is supposed to be helping us to produce good code, but our productivity hits a wall every time we need to please our CI overlords. As a result, they make us lose many times more productivity than we could ever hope to gain from it. Typically this week, our functionality has been up and running since Tuesday ; adapting the old tests was much faster and easier to do with the proper abstraction and was finished today (Wednesday). But then, turns out we need to bump the SDK to 24 to be able to use java.util.Optional ; make java compat version to 1.8 so we can use lambdas instead of the legacy heavyweight syntax for defining listeners and the like ; and chaos ensues on Travis. We are feeling very distressed, after all the hours we spent, all the work we did and all the things we learned this week, to hit artificial walls. 

Could you please take a look at branch Follow (which ended up superseding refactor/commonAbstraction since the auth abstraction was done on it) and how we can make it work with SDK 24 on Travis? Which solution should we take to avoid the production-side code tanking our coverage?

**Comment by Gondolav** [comment]
Let me understand, everything worked just fine before upgrading to Java 8?

Also, 600 untested lines sounds too much.
