### ISSUE TITLE
Proliferation of interface methods

### ISSUE THREAD

**Issue by AntoineSidem** [KandleTeam/kandle#91]
We are starting to have a lot of methods in the Database interface, for getting users, updating users, following, unfollowing... and any high-level operation that is directly useful for the application. More methods are added every time a new kind of operation appears.

I am tempted to say the following: it is not a problem to proliferate methods in the Database interface, as the database abstraction is supposed to give access to high-level operations on users, followings, etc ; as long as the implementation of these methods is as factorized as possible (even though it isn't exactly the case as of now). Do you agree? If not, do you have a suggestion to have a more succinct database interface? 

It appears difficult to make the interface shorter without changing the level of abstraction altogether. For example, we could define a implementation-independent, contractual filesystem for Databases and expose something like:
```
Object getResource(String unified/path/to/resource);
void setResource(String unified/path/to/resource, Object newResource);
```
and infer the intended operation via parsing and casting inside the implementation class. That would make the Database interface practically constant-length, letting the implementations take care of supporting increasing functionality. It would also make decorating a database (for example for caching) that much more elegant. On the other hand, the implementation code might be more complex, and support for functionality is no longer enforced by the language. 

We are also considering merging the current Database (mirroring Firestore) and Storage (mirroring Cloud Storage for images etc.) into a single Database - after all, they are conceptually very similar.

Do you have any design comment before we commit to the current design?

**Comment by Gondolav** [comment]
Hi! We think it is not a big deal having many methods in your Database interface, and your intuition is correct, so you don’t need to change it. Concerning Cloud Storage, we strongly suggest you to keep them separated.
